//! `.BUILDINFO` generator.
//!
//! Records build environment details for reproducibility and auditing:
//! packager identity, build date, toolchain versions, build directory,
//! and environment flags used during compilation.

use crate::config::XpkgConfig;
use crate::recipe::Recipe;
use crate::repro;

use super::BuildProvenance;

/// Generate the `.BUILDINFO` file content.
///
/// The historical `key = value` format is preserved; extended provenance
/// fields (`x:source_commit`, `x:source_url`, `x:source_sha256`,
/// `x:recipe_sha256`, `x:tool_version`) are appended at the end and ignored by
/// readers that do not know them.
pub fn generate_buildinfo(
    recipe: &Recipe,
    config: &XpkgConfig,
    provenance: &BuildProvenance,
) -> String {
    let pkg = &recipe.package;
    let mut out = String::new();

    // Header.
    out.push_str("# Generated by xpkg\n");

    // Package identity.
    out.push_str(&format!("pkgname = {}\n", pkg.name));
    out.push_str(&format!("pkgver = {}-{}\n", pkg.version, pkg.release));

    // Build environment.
    out.push_str(&format!("builddate = {}\n", repro::build_timestamp()));
    out.push_str(&format!(
        "builddir = {}\n",
        config.options.builddir.display()
    ));
    out.push_str(&format!("buildtool = xpkg {}\n", env!("CARGO_PKG_VERSION")));

    // System info.
    if let Ok(hostname) = std::env::var("HOSTNAME") {
        out.push_str(&format!("buildhost = {hostname}\n"));
    }

    // Environment flags.
    let env = &config.environment;
    if !env.cflags.is_empty() {
        out.push_str(&format!("CFLAGS = {}\n", env.cflags));
    }
    if !env.cxxflags.is_empty() {
        out.push_str(&format!("CXXFLAGS = {}\n", env.cxxflags));
    }
    if !env.ldflags.is_empty() {
        out.push_str(&format!("LDFLAGS = {}\n", env.ldflags));
    }
    if !env.makeflags.is_empty() {
        out.push_str(&format!("MAKEFLAGS = {}\n", env.makeflags));
    }

    // Compression settings.
    out.push_str(&format!("compress = {}\n", config.options.compress));
    out.push_str(&format!(
        "compress_level = {}\n",
        config.options.compress_level
    ));

    // Extended provenance (backward compatible: unknown keys are ignored).
    if let Some(commit) = &provenance.source_commit {
        out.push_str(&format!("x:source_commit = {commit}\n"));
    }
    // Source provenance straight from the recipe: first URL and its pinned
    // checksum, so history.json can record downgrade provenance without
    // re-reading the recipe. "SKIP" checksums are not provenance.
    if let Some(url) = recipe.source.urls.first() {
        out.push_str(&format!("x:source_url = {url}\n"));
    }
    if let Some(sum) = recipe.source.sha256sums.first() {
        if sum != "SKIP" {
            out.push_str(&format!("x:source_sha256 = {sum}\n"));
        }
    }
    if let Some(sha256) = &provenance.recipe_sha256 {
        out.push_str(&format!("x:recipe_sha256 = {sha256}\n"));
    }
    out.push_str(&format!("x:tool_version = {}\n", env!("CARGO_PKG_VERSION")));

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::recipe::{BuildSection, DependencySection, PackageSection, Recipe, SourceSection};

    fn test_recipe() -> Recipe {
        Recipe {
            package: PackageSection {
                name: "test-pkg".into(),
                version: "2.0".into(),
                release: 3,
                description: "Test".into(),
                url: None,
                license: vec![],
                arch: vec!["x86_64".into()],
                provides: vec![],
                conflicts: vec![],
                replaces: vec![],
            },
            dependencies: DependencySection::default(),
            source: SourceSection::default(),
            build: BuildSection::default(),
        }
    }

    #[test]
    fn test_buildinfo_contains_package_identity() {
        let info = generate_buildinfo(
            &test_recipe(),
            &XpkgConfig::default(),
            &BuildProvenance::default(),
        );
        assert!(info.contains("pkgname = test-pkg\n"));
        assert!(info.contains("pkgver = 2.0-3\n"));
    }

    #[test]
    fn test_buildinfo_contains_buildtool() {
        let info = generate_buildinfo(
            &test_recipe(),
            &XpkgConfig::default(),
            &BuildProvenance::default(),
        );
        assert!(info.contains("buildtool = xpkg "));
    }

    #[test]
    fn test_buildinfo_contains_environment_flags() {
        let config = XpkgConfig::default();
        let info = generate_buildinfo(&test_recipe(), &config, &BuildProvenance::default());
        assert!(info.contains("CFLAGS = -march=x86-64 -O2 -pipe\n"));
        assert!(info.contains("CXXFLAGS = -march=x86-64 -O2 -pipe\n"));
        assert!(info.contains("MAKEFLAGS = -j$(nproc)\n"));
    }

    #[test]
    fn test_buildinfo_omits_empty_ldflags() {
        let config = XpkgConfig::default();
        let info = generate_buildinfo(&test_recipe(), &config, &BuildProvenance::default());
        assert!(!info.contains("LDFLAGS"));
    }

    #[test]
    fn test_buildinfo_contains_compression() {
        let info = generate_buildinfo(
            &test_recipe(),
            &XpkgConfig::default(),
            &BuildProvenance::default(),
        );
        assert!(info.contains("compress = zstd\n"));
        assert!(info.contains("compress_level = 19\n"));
    }

    #[test]
    fn test_buildinfo_contains_extended_provenance() {
        let provenance = BuildProvenance {
            recipe_sha256: Some("abc123".into()),
            source_commit: Some("deadbeef".into()),
        };
        let info = generate_buildinfo(&test_recipe(), &XpkgConfig::default(), &provenance);

        assert!(info.contains("x:source_commit = deadbeef\n"));
        assert!(info.contains("x:recipe_sha256 = abc123\n"));
        assert!(info.contains(&format!("x:tool_version = {}\n", env!("CARGO_PKG_VERSION"))));
    }

    #[test]
    fn test_buildinfo_records_recipe_source_url_and_checksum() {
        let mut recipe = test_recipe();
        recipe.source.urls = vec!["https://example.com/pkg-1.0.tar.gz".into()];
        recipe.source.sha256sums = vec!["cafe1234".into()];

        let info = generate_buildinfo(&recipe, &XpkgConfig::default(), &BuildProvenance::default());

        assert!(info.contains("x:source_url = https://example.com/pkg-1.0.tar.gz\n"));
        assert!(info.contains("x:source_sha256 = cafe1234\n"));
    }

    #[test]
    fn test_buildinfo_skips_skip_checksums() {
        let mut recipe = test_recipe();
        recipe.source.urls = vec!["git+https://example.com/repo.git#commit=deadbeef".into()];
        recipe.source.sha256sums = vec!["SKIP".into()];

        let info = generate_buildinfo(&recipe, &XpkgConfig::default(), &BuildProvenance::default());

        assert!(info.contains("x:source_url = git+https://example.com/repo.git#commit=deadbeef\n"));
        assert!(!info.contains("x:source_sha256"));
    }

    #[test]
    fn test_buildinfo_appends_extended_fields_at_the_end() {
        let provenance = BuildProvenance {
            recipe_sha256: Some("abc123".into()),
            source_commit: Some("deadbeef".into()),
        };
        let info = generate_buildinfo(&test_recipe(), &XpkgConfig::default(), &provenance);

        // The historical format is untouched and the new keys come last.
        let compress_pos = info.find("compress_level = 19").unwrap();
        let commit_pos = info.find("x:source_commit").unwrap();
        let recipe_pos = info.find("x:recipe_sha256").unwrap();
        let tool_pos = info.find("x:tool_version").unwrap();
        assert!(compress_pos < commit_pos);
        assert!(commit_pos < recipe_pos);
        assert!(recipe_pos < tool_pos);
        assert!(info.ends_with(&format!("x:tool_version = {}\n", env!("CARGO_PKG_VERSION"))));
    }

    #[test]
    fn test_buildinfo_omits_unavailable_provenance() {
        let info = generate_buildinfo(
            &test_recipe(),
            &XpkgConfig::default(),
            &BuildProvenance::default(),
        );
        assert!(!info.contains("x:source_commit"));
        assert!(!info.contains("x:recipe_sha256"));
    }
}
